#!/usr/bin/env node

const chalk = require('chalk');
const fs = require('fs');
const glob = require('glob');
const numeral = require('numeral');

const pattern = process.argv[2];
const files = glob.sync(pattern);

files.forEach((file) => {
    const input = fs.readFileSync(file, 'utf8');
    const output = minifyJson(input);

    fs.writeFileSync(file, output, 'utf8');

    console.log(`Minified ${chalk.green(file)} from ${formatSize(input)} to ${formatSize(output)}`);
});

function formatSize(content) {
    return numeral(Buffer.from(content).length).format('0.00 ib');
}

function minifyJson(content) {
    return JSON.stringify(JSON.parse(content), null, '');
}
